[package]
name = "mc_stack"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0"
env_logger = "0"
log = "0"
num_cpus = "1"
tokio = { version = "1", features = ["full", "fs"] }
serde_json = "1"
walkdir = "2"
regex = "1"
rust-embed = "6"
mime_guess = "2"