services:
  mc_stack:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/excoffierleonard/mc_stack
    container_name: mc_stack
    ports:
      - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - mc_stack:/mc_stack/stacks
    networks:
      - mc_stack
    restart: unless-stopped	

volumes:
  mc_stack:
    name: mc_stack

networks:
  mc_stack:
    name: mc_stack
