name: Build, push and deploy to production

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Copy compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "compose.yaml"
          target: "/home/${{ secrets.PROD_USERNAME }}/${{ github.event.repository.name }}/"

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            export COMPOSE_PATH="/home/${{ secrets.PROD_USERNAME }}/${{ github.event.repository.name }}/compose.yaml"
            # Create docker config directory if it doesn't exist
            mkdir -p ~/.docker
            # Login using docker config to avoid token in shell history
            echo '{ "auths": { "ghcr.io": { "auth": "${{ secrets.GITHUB_TOKEN }}" } } }' > ~/.docker/config.json
            docker compose -f $COMPOSE_PATH pull
            docker compose -f $COMPOSE_PATH down
            docker compose -f $COMPOSE_PATH up -d
            # Remove the config file after we're done
            rm ~/.docker/config.json
